export * from './listActions';
export * from './cardAction';


export const CONSTANTS = {
    ADD_NEW_BOARD: 'ADD_NEW_BOARD',
    SET_CURRENT_BOARD: 'SET_CURRENT_BOARD',
    ADD_CARD : 'ADD_CARD',
    ADD_LIST: 'ADD_LIST',
    DRAG_HAPPENED: 'DRAG_HAPPENED',
    EDIT_CARD_DESCRIPTION: 'EDIT_CARD_DESCRIPTION',
    EDIT_CARD_TITLE: 'EDIT_CARD_TITLE',
    ADD_CARD_LIST_ITEM: 'ADD_CARD_LIST_ITEM',
    SET_ITEM_AS_CHECKED: 'SET_ITEM_AS_CHECKED',
    ADD_COMMENT: 'ADD_COMMENT'
};